/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lastninja_monocypher_Monocypher */

#ifndef _Included_net_lastninja_monocypher_Monocypher
#define _Included_net_lastninja_monocypher_Monocypher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify16
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify16
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify32
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify32
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify64
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify64
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_wipe
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1wipe
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
