/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lastninja_monocypher_Monocypher */

#ifndef _Included_net_lastninja_monocypher_Monocypher
#define _Included_net_lastninja_monocypher_Monocypher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify16
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify16
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify32
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify32
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_verify64
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1verify64
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_wipe
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1wipe___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_lock
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[BLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1lock
  (JNIEnv *, jobject, jobject, jobject, jbyteArray, jobject, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_unlock
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[BLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1unlock
  (JNIEnv *, jobject, jobject, jobject, jbyteArray, jobject, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_init_x
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;[B[B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1init_1x
  (JNIEnv *, jobject, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_init_djb
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;[B[B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1init_1djb
  (JNIEnv *, jobject, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_init_ietf
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;[B[B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1init_1ietf
  (JNIEnv *, jobject, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_wipe
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1wipe__Lnet_lastninja_monocypher_Monocypher_00024AEAD_1ctx_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_write
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1write
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_aead_read
 * Signature: (Lnet/lastninja/monocypher/Monocypher/AEAD_ctx;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1aead_1read
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_blake2b
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1blake2b
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_blake2b_keyed
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1blake2b_1keyed
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     net_lastninja_monocypher_Monocypher
 * Method:    crypto_blake2b_init
 * Signature: (Lnet/lastninja/monocypher/Monocypher/Blake2b_ctx;J)V
 */
JNIEXPORT void JNICALL Java_net_lastninja_monocypher_Monocypher_crypto_1blake2b_1init
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
